# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_code', models.CharField(max_length=30)),
                ('exData', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
